# Generated by Django 5.1.7 on 2025-06-23 20:26

import django.db.models.deletion
import leaderboard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_userprofile_score_semanal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('codigo_convite', models.CharField(default=leaderboard.models.gerar_codigo_convite, help_text='Código para ingresso na liga.', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'liga',
                'verbose_name_plural': 'ligas',
            },
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(default=0)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='leaderboard.competidor')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='leaderboard.liga')),
            ],
            options={
                'verbose_name': 'participação',
                'verbose_name_plural': 'participações',
                'unique_together': {('competidor', 'liga')},
            },
        ),
        migrations.AddField(
            model_name='liga',
            name='competidores',
            field=models.ManyToManyField(related_name='ligas', through='leaderboard.Participacao', to='leaderboard.competidor'),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='leaderboard.liga')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='users.userprofile')),
            ],
            options={
                'ordering': ['posicao'],
                'unique_together': {('perfil', 'liga')},
            },
        ),
    ]
