# Generated by Django 5.1.7 on 2025-06-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='score_semanal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score_total',
        ),
    ]
